FROM grafana/grafana:latest

ENV GF_SECURITY_ADMIN_USER=admin \
    GF_SECURITY_ADMIN_PASSWORD=1234 \
    GF_AUTH_ANONYMOUS_ENABLED=false \
    GF_SECURITY_ALLOW_EMBEDDING=true \
    GF_SECURITY_COOKIE_SAMESITE=none \
    GF_SECURITY_COOKIE_SECURE=true

EXPOSE 3000

