{
 "title": "admin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tabla de tareas mejorada",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT \r\n  t.title AS \"Task\",\r\n  (t.date + COALESCE(t.\"time\", TIME '00:00')) AS \"Due\",\r\n  CASE\r\n    WHEN (t.date + COALESCE(t.\"time\", TIME '00:00')) < NOW() THEN 'Overdue'\r\n    WHEN t.date = CURRENT_DATE THEN 'Today'\r\n    ELSE 'Upcoming'\r\n  END AS \"Priority\",\r\n  t.status AS \"Status\",\r\n  COALESCE(u.name, 'Unassigned') AS \"Assigned To\",\r\n  COALESCE(l.name, '-') AS \"Lot\",\r\n  COALESCE(a.code, '-') AS \"Animal\"\r\nFROM task t\r\nLEFT JOIN user_app u ON u.user_id = t.assigned_user_id\r\nLEFT JOIN lot l      ON l.lot_id = t.lot_id\r\nLEFT JOIN animal a   ON a.animal_id = t.animal_id\r\nWHERE t.status IN ('pending','in_progress')\r\nORDER BY \"Due\" ASC\r\nLIMIT 30;\r\n"
    }
   ]
  },
  {
   "title": "Food costs for the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT\r\n  (date_time)::date AS \"Day\",\r\n  COALESCE(SUM(cost),0) AS \"Feeding Cost\"\r\nFROM feeding\r\nWHERE (date_time)::date >= (CURRENT_DATE - INTERVAL '6 days')::date\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Animals per lot",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT\r\n  l.name AS \"Lot\",\r\n  COUNT(a.animal_id) AS \"Animals\"\r\nFROM animal a\r\nJOIN lot l ON l.lot_id = a.lot_id\r\nGROUP BY l.name\r\nORDER BY COUNT(a.animal_id) DESC;\r\n"
    }
   ]
  },
  {
   "title": "animal active",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT COUNT(*) AS \"Active Animals\"\r\nFROM animal\r\nWHERE status = 'active';\r\n"
    }
   ]
  },
  {
   "title": "Production last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT\r\n  (\"date\")::date AS \"Day\",\r\n  COALESCE(SUM(quantity),0) AS \"Total Production\"\r\nFROM production\r\nWHERE (\"date\")::date >= (CURRENT_DATE - INTERVAL '6 days')::date\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}