{
 "title": "Super admin",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT\r\n  DATE_TRUNC('day', date) AS \"time\",\r\n  SUM(quantity) AS \"Total Production\"\r\nFROM production\r\nGROUP BY DATE_TRUNC('day', date)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Total Animals",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT COUNT(*) AS \"Total Animals\"\r\nFROM animal;"
    }
   ]
  },
  {
   "title": "Total  of tenants",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT COUNT(*) AS \"Total tenants\"\r\nFROM tenant;"
    }
   ]
  },
  {
   "title": "Animals per tenant",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "agrotrack",
     "rawSql": "SELECT\r\n  t.name AS \"Tenant\",\r\n  COUNT(a.animal_id) AS \"Animal Count\"\r\nFROM tenant t\r\nLEFT JOIN animal a ON a.tenant_id = t.tenant_id\r\nGROUP BY t.name;"
    }
   ]
  }
 ]
}